const BattleRoyaleRandom = artifacts.require("BattleRoyaleRandom");
const { BN } = require("web3-utils");

module.exports = async function (deployer) {
  await deployer.deploy(
    BattleRoyaleRandom,
    "NiftyRoyale",
    "NYR",
    new BN('10000000000000000'),
    5,
    100,
    ["https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/1.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/2.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/3.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/4.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/5.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/6.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/7.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/8.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/9.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/10.json",
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/1.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/2.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/3.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/4.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/5.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/6.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/7.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/8.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/9.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/10.json",
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/1.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/2.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/3.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/4.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/5.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/6.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/7.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/8.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/9.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/10.json",
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/1.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/2.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/3.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/4.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/5.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/6.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/7.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/8.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/9.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/10.json",
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/1.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/2.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/3.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/4.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/5.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/6.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/7.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/8.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/9.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/10.json",
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/1.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/2.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/3.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/4.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/5.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/6.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/7.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/8.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/9.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/10.json",
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/1.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/2.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/3.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/4.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/5.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/6.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/7.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/8.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/9.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/10.json",
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/1.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/2.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/3.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/4.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/5.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/6.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/7.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/8.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/9.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/10.json",
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/1.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/2.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/3.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/4.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/5.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/6.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/7.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/8.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/9.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/10.json",
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/1.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/2.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/3.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/4.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/5.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/6.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/7.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/8.json", 
    "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/9.json", "https://niftyroyale.mypinata.cloud/ipfs/QmPodCXBaLAvuqyyW68XcMChnUGG6WiuraH7UXs7jF5iiF/10.json"]
  );

  return;
};
